
import java.awt.Color;
import static java.awt.Color.WHITE;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Diego Vasquez
 */
public class Lab extends javax.swing.JFrame {

    /**
     * Creates new form Lab
     */
    public Lab() {
        initComponents();
        try {
            LeerVehiculos();
        } catch (IOException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            LeerVendedores();
        } catch (Exception e) {
        }
        try {
            LeerClientes();
        } catch (IOException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            LeerVentas();
        } catch (IOException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_BackGround = new javax.swing.JPanel();
        jt_YUH = new javax.swing.JTabbedPane();
        jp_Vehiculos = new javax.swing.JPanel();
        jl_Marca = new javax.swing.JLabel();
        jt_Marca = new javax.swing.JTextField();
        JL_ColorVehiculo = new javax.swing.JLabel();
        jl_modelo = new javax.swing.JLabel();
        jt_Modelo = new javax.swing.JTextField();
        jl_años = new javax.swing.JLabel();
        jt_Años = new javax.swing.JTextField();
        jl_precio = new javax.swing.JLabel();
        jt_Precio = new javax.swing.JTextField();
        jb_AgregarVehiculo = new javax.swing.JButton();
        jl_Titulo = new javax.swing.JLabel();
        jt_ColorCarro = new javax.swing.JTextField();
        jp_Vendedores = new javax.swing.JPanel();
        jl_NombreVendedor = new javax.swing.JLabel();
        jt_NombreVendedor = new javax.swing.JTextField();
        jl_CantVendidosVendedor = new javax.swing.JLabel();
        jt_CantVendidosVend = new javax.swing.JTextField();
        jl_DineroGeneradoVendedor = new javax.swing.JLabel();
        jt_DineroGeneradoVendedor = new javax.swing.JTextField();
        jb_AgregarVendedor = new javax.swing.JButton();
        jl_Titulo1 = new javax.swing.JLabel();
        jp_Clientes = new javax.swing.JPanel();
        jl_NombreCliente = new javax.swing.JLabel();
        jt_NombreCliente = new javax.swing.JTextField();
        JL_EdadCliente = new javax.swing.JLabel();
        jl_ProfesionCliente = new javax.swing.JLabel();
        jt_ProfesionCliente = new javax.swing.JTextField();
        jl_CantCarrosCliente = new javax.swing.JLabel();
        jt_CantCarrosCliente = new javax.swing.JTextField();
        jl_SueldoCliente = new javax.swing.JLabel();
        jt_SueldoCliente = new javax.swing.JTextField();
        jt_EdadCliente = new javax.swing.JTextField();
        jb_AgregarCliente = new javax.swing.JButton();
        jl_Titulo2 = new javax.swing.JLabel();
        jp_Venta = new javax.swing.JPanel();
        jl_VendedoresDisponibles = new javax.swing.JLabel();
        cb_VendedoresDisponibles = new javax.swing.JComboBox<>();
        jl_ClientesDisp = new javax.swing.JLabel();
        cb_ClientesDisponibles = new javax.swing.JComboBox<>();
        jl_VehiculosDisponibles = new javax.swing.JLabel();
        cb_VehiculosDisponibles = new javax.swing.JComboBox<>();
        jb_AgregarVenta = new javax.swing.JButton();
        jl_Titulo3 = new javax.swing.JLabel();
        jb_TerminarDia = new javax.swing.JButton();
        jb_UpdateComboboxes = new javax.swing.JButton();
        jp_TextPane = new javax.swing.JPanel();
        jl_ListarVendedores = new javax.swing.JLabel();
        jl_ListarClientes = new javax.swing.JLabel();
        jl_ListarVehiculos = new javax.swing.JLabel();
        jb_listarVendedores = new javax.swing.JButton();
        jb_ListarClientes = new javax.swing.JButton();
        jb_listarVehiculos = new javax.swing.JButton();
        jl_ListarVentas = new javax.swing.JLabel();
        jb_listarVentas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_editar = new javax.swing.JTextPane();
        jb_Guardar = new javax.swing.JButton();
        jp_Jtrees = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtree_Admin = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtree_Dias = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_BackGround.setBackground(new java.awt.Color(204, 255, 204));
        jp_BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_Vehiculos.setBackground(new java.awt.Color(255, 102, 102));

        jl_Marca.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_Marca.setForeground(new java.awt.Color(0, 0, 0));
        jl_Marca.setText("Marca:");

        JL_ColorVehiculo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JL_ColorVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        JL_ColorVehiculo.setText("COLOR:");

        jl_modelo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_modelo.setForeground(new java.awt.Color(0, 0, 0));
        jl_modelo.setText("Modelo:");

        jl_años.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_años.setForeground(new java.awt.Color(0, 0, 0));
        jl_años.setText("Años Usado:");

        jl_precio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_precio.setForeground(new java.awt.Color(0, 0, 0));
        jl_precio.setText("Precio:");

        jb_AgregarVehiculo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jb_AgregarVehiculo.setForeground(new java.awt.Color(0, 0, 0));
        jb_AgregarVehiculo.setText("¡AGREGAR!");
        jb_AgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AgregarVehiculoActionPerformed(evt);
            }
        });

        jl_Titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jl_Titulo.setForeground(new java.awt.Color(0, 0, 0));
        jl_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Titulo.setText("Crear Vehiculos");

        javax.swing.GroupLayout jp_VehiculosLayout = new javax.swing.GroupLayout(jp_Vehiculos);
        jp_Vehiculos.setLayout(jp_VehiculosLayout);
        jp_VehiculosLayout.setHorizontalGroup(
            jp_VehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_VehiculosLayout.createSequentialGroup()
                .addGroup(jp_VehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_VehiculosLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jp_VehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_VehiculosLayout.createSequentialGroup()
                                .addComponent(jl_precio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_Precio))
                            .addGroup(jp_VehiculosLayout.createSequentialGroup()
                                .addComponent(jl_Marca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_Marca))
                            .addGroup(jp_VehiculosLayout.createSequentialGroup()
                                .addComponent(JL_ColorVehiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_ColorCarro))
                            .addGroup(jp_VehiculosLayout.createSequentialGroup()
                                .addComponent(jl_modelo)
                                .addGap(18, 18, 18)
                                .addComponent(jt_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_VehiculosLayout.createSequentialGroup()
                                .addComponent(jl_años)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_Años, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_VehiculosLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jb_AgregarVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_VehiculosLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jp_VehiculosLayout.setVerticalGroup(
            jp_VehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_VehiculosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jp_VehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_VehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_ColorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_ColorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jp_VehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_VehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_años, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_VehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jb_AgregarVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(108, 108, 108))
        );

        jt_YUH.addTab("Vehiculos", jp_Vehiculos);

        jp_Vendedores.setBackground(new java.awt.Color(255, 51, 51));

        jl_NombreVendedor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_NombreVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jl_NombreVendedor.setText("Nombre:");

        jl_CantVendidosVendedor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_CantVendidosVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jl_CantVendidosVendedor.setText("Cantidad de Autos Vendidos: ");

        jl_DineroGeneradoVendedor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_DineroGeneradoVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jl_DineroGeneradoVendedor.setText("Dinero Generado:");

        jb_AgregarVendedor.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jb_AgregarVendedor.setForeground(new java.awt.Color(0, 0, 0));
        jb_AgregarVendedor.setText("¡AGREGAR!");
        jb_AgregarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AgregarVendedorActionPerformed(evt);
            }
        });

        jl_Titulo1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jl_Titulo1.setForeground(new java.awt.Color(0, 0, 0));
        jl_Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Titulo1.setText("Crear Vendedores");

        javax.swing.GroupLayout jp_VendedoresLayout = new javax.swing.GroupLayout(jp_Vendedores);
        jp_Vendedores.setLayout(jp_VendedoresLayout);
        jp_VendedoresLayout.setHorizontalGroup(
            jp_VendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_VendedoresLayout.createSequentialGroup()
                .addGroup(jp_VendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_VendedoresLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jb_AgregarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_VendedoresLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jp_VendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_VendedoresLayout.createSequentialGroup()
                                .addComponent(jl_DineroGeneradoVendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jt_DineroGeneradoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_VendedoresLayout.createSequentialGroup()
                                .addComponent(jl_CantVendidosVendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt_CantVendidosVend, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_VendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jl_Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jp_VendedoresLayout.createSequentialGroup()
                                    .addComponent(jl_NombreVendedor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jt_NombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jp_VendedoresLayout.setVerticalGroup(
            jp_VendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_VendedoresLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jl_Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jp_VendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_NombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jp_VendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_CantVendidosVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_CantVendidosVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jp_VendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_DineroGeneradoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_DineroGeneradoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jb_AgregarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(107, 107, 107))
        );

        jt_YUH.addTab("Vendedores", jp_Vendedores);

        jp_Clientes.setBackground(new java.awt.Color(204, 0, 51));

        jl_NombreCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_NombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        jl_NombreCliente.setText("Nombre:");

        JL_EdadCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        JL_EdadCliente.setForeground(new java.awt.Color(0, 0, 0));
        JL_EdadCliente.setText("Edad:");

        jl_ProfesionCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_ProfesionCliente.setForeground(new java.awt.Color(0, 0, 0));
        jl_ProfesionCliente.setText("Profesion:");

        jl_CantCarrosCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_CantCarrosCliente.setForeground(new java.awt.Color(0, 0, 0));
        jl_CantCarrosCliente.setText("Carros Comprados:");

        jl_SueldoCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_SueldoCliente.setForeground(new java.awt.Color(0, 0, 0));
        jl_SueldoCliente.setText("Sueldo:");

        jb_AgregarCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jb_AgregarCliente.setForeground(new java.awt.Color(0, 0, 0));
        jb_AgregarCliente.setText("¡AGREGAR!");
        jb_AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AgregarClienteActionPerformed(evt);
            }
        });

        jl_Titulo2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jl_Titulo2.setForeground(new java.awt.Color(0, 0, 0));
        jl_Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Titulo2.setText("Crear Clientes");

        javax.swing.GroupLayout jp_ClientesLayout = new javax.swing.GroupLayout(jp_Clientes);
        jp_Clientes.setLayout(jp_ClientesLayout);
        jp_ClientesLayout.setHorizontalGroup(
            jp_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ClientesLayout.createSequentialGroup()
                .addGroup(jp_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_ClientesLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jb_AgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_ClientesLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(jp_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jp_ClientesLayout.createSequentialGroup()
                                    .addComponent(jl_SueldoCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jt_SueldoCliente))
                                .addGroup(jp_ClientesLayout.createSequentialGroup()
                                    .addComponent(jl_NombreCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jt_NombreCliente))
                                .addGroup(jp_ClientesLayout.createSequentialGroup()
                                    .addComponent(JL_EdadCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jt_EdadCliente))
                                .addGroup(jp_ClientesLayout.createSequentialGroup()
                                    .addComponent(jl_ProfesionCliente)
                                    .addGap(18, 18, 18)
                                    .addComponent(jt_ProfesionCliente))
                                .addGroup(jp_ClientesLayout.createSequentialGroup()
                                    .addComponent(jl_CantCarrosCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jt_CantCarrosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jp_ClientesLayout.setVerticalGroup(
            jp_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ClientesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jl_Titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jp_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_EdadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_EdadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ProfesionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_ProfesionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_CantCarrosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_CantCarrosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_SueldoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_SueldoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jb_AgregarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(96, 96, 96))
        );

        jt_YUH.addTab("Clientes", jp_Clientes);

        jp_Venta.setBackground(new java.awt.Color(153, 0, 51));

        jl_VendedoresDisponibles.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_VendedoresDisponibles.setForeground(new java.awt.Color(0, 0, 0));
        jl_VendedoresDisponibles.setText("Vendedores Disponibles:");

        jl_ClientesDisp.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_ClientesDisp.setForeground(new java.awt.Color(0, 0, 0));
        jl_ClientesDisp.setText("Clientes Disponibles:");

        jl_VehiculosDisponibles.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_VehiculosDisponibles.setForeground(new java.awt.Color(0, 0, 0));
        jl_VehiculosDisponibles.setText("Vehiculos Disponibles:");

        jb_AgregarVenta.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jb_AgregarVenta.setForeground(new java.awt.Color(0, 0, 0));
        jb_AgregarVenta.setText("!VENDER¡");
        jb_AgregarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AgregarVentaActionPerformed(evt);
            }
        });

        jl_Titulo3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jl_Titulo3.setForeground(new java.awt.Color(0, 0, 0));
        jl_Titulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Titulo3.setText("Realizar Venta:");

        jb_TerminarDia.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jb_TerminarDia.setForeground(new java.awt.Color(0, 0, 0));
        jb_TerminarDia.setText("Terminar Dia");
        jb_TerminarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_TerminarDiaActionPerformed(evt);
            }
        });

        jb_UpdateComboboxes.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jb_UpdateComboboxes.setForeground(new java.awt.Color(0, 0, 0));
        jb_UpdateComboboxes.setText("Update CB´s");
        jb_UpdateComboboxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_UpdateComboboxesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_VentaLayout = new javax.swing.GroupLayout(jp_Venta);
        jp_Venta.setLayout(jp_VentaLayout);
        jp_VentaLayout.setHorizontalGroup(
            jp_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_VentaLayout.createSequentialGroup()
                .addGroup(jp_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_VentaLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jp_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_VentaLayout.createSequentialGroup()
                                .addComponent(jl_VehiculosDisponibles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_VehiculosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_VentaLayout.createSequentialGroup()
                                .addComponent(jl_ClientesDisp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_ClientesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_VentaLayout.createSequentialGroup()
                                .addComponent(jl_VendedoresDisponibles)
                                .addGap(18, 18, 18)
                                .addComponent(cb_VendedoresDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_VentaLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jb_AgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_VentaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jb_TerminarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jp_VentaLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jl_Titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_UpdateComboboxes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_VentaLayout.setVerticalGroup(
            jp_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_VentaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jp_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_UpdateComboboxes))
                .addGap(50, 50, 50)
                .addGroup(jp_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_VendedoresDisponibles)
                    .addComponent(cb_VendedoresDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jp_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ClientesDisp)
                    .addComponent(cb_ClientesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jp_VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_VehiculosDisponibles)
                    .addComponent(cb_VehiculosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jb_AgregarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(73, 73, 73)
                .addComponent(jb_TerminarDia, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jt_YUH.addTab("Ventas", jp_Venta);

        jp_TextPane.setBackground(new java.awt.Color(153, 51, 0));

        jl_ListarVendedores.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_ListarVendedores.setForeground(new java.awt.Color(0, 0, 0));
        jl_ListarVendedores.setText("VENDEDORES");

        jl_ListarClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_ListarClientes.setForeground(new java.awt.Color(0, 0, 0));
        jl_ListarClientes.setText("CLIENTES");

        jl_ListarVehiculos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_ListarVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        jl_ListarVehiculos.setText("CARROS");

        jb_listarVendedores.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jb_listarVendedores.setForeground(new java.awt.Color(0, 0, 0));
        jb_listarVendedores.setText("Listar sellers:");
        jb_listarVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_listarVendedoresActionPerformed(evt);
            }
        });

        jb_ListarClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jb_ListarClientes.setForeground(new java.awt.Color(0, 0, 0));
        jb_ListarClientes.setText("Listar Clientes:");
        jb_ListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ListarClientesActionPerformed(evt);
            }
        });

        jb_listarVehiculos.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jb_listarVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        jb_listarVehiculos.setText("Listar Carros:");
        jb_listarVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_listarVehiculosActionPerformed(evt);
            }
        });

        jl_ListarVentas.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jl_ListarVentas.setForeground(new java.awt.Color(0, 0, 0));
        jl_ListarVentas.setText("VENTAS");

        jb_listarVentas.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jb_listarVentas.setForeground(new java.awt.Color(0, 0, 0));
        jb_listarVentas.setText("Listar Ventas:");
        jb_listarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_listarVentasActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jt_editar);

        jb_Guardar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jb_Guardar.setForeground(new java.awt.Color(0, 0, 0));
        jb_Guardar.setText("GUARDAR");
        jb_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_TextPaneLayout = new javax.swing.GroupLayout(jp_TextPane);
        jp_TextPane.setLayout(jp_TextPaneLayout);
        jp_TextPaneLayout.setHorizontalGroup(
            jp_TextPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_TextPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_TextPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_ListarClientes)
                    .addComponent(jb_listarVentas)
                    .addComponent(jb_listarVehiculos)
                    .addGroup(jp_TextPaneLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jl_ListarVentas))
                    .addGroup(jp_TextPaneLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jl_ListarVehiculos))
                    .addGroup(jp_TextPaneLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jl_ListarClientes))
                    .addGroup(jp_TextPaneLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jb_listarVendedores))
                    .addGroup(jp_TextPaneLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jl_ListarVendedores)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_TextPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_Guardar)
                .addGap(109, 109, 109))
        );
        jp_TextPaneLayout.setVerticalGroup(
            jp_TextPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_TextPaneLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jl_ListarVendedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_listarVendedores)
                .addGap(27, 27, 27)
                .addComponent(jl_ListarClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_ListarClientes)
                .addGap(38, 38, 38)
                .addComponent(jl_ListarVehiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_listarVehiculos)
                .addGap(42, 42, 42)
                .addComponent(jl_ListarVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_listarVentas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_TextPaneLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_Guardar)
                .addGap(61, 61, 61))
        );

        jt_YUH.addTab("TextPane (Editar)", jp_TextPane);

        jp_Jtrees.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Admin");
        jtree_Admin.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree_AdminMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtree_Admin);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Dia");
        jtree_Dias.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree_Dias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree_DiasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtree_Dias);

        javax.swing.GroupLayout jp_JtreesLayout = new javax.swing.GroupLayout(jp_Jtrees);
        jp_Jtrees.setLayout(jp_JtreesLayout);
        jp_JtreesLayout.setHorizontalGroup(
            jp_JtreesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_JtreesLayout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jp_JtreesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_JtreesLayout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(360, Short.MAX_VALUE)))
        );
        jp_JtreesLayout.setVerticalGroup(
            jp_JtreesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_JtreesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jp_JtreesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_JtreesLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        jt_YUH.addTab("Jtrees", jp_Jtrees);

        jp_BackGround.add(jt_YUH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_AgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AgregarVehiculoActionPerformed
        // TODO add your handling code here:
        try {
            String marca = jt_Marca.getText();
            String color = jt_ColorCarro.getText();
            String modelo = jt_Modelo.getText();
            int años = Integer.parseInt(jt_Años.getText());
            double precio = Double.parseDouble(jt_Precio.getText());

            Vehiculo v = new Vehiculo(marca, color, modelo, años, precio);
            carros.add(v);

            jt_Marca.setText("");
            jt_Modelo.setText("");
            jt_ColorCarro.setText("");
            jt_Años.setText("");
            jt_Precio.setText("");

            JOptionPane.showMessageDialog(this, "Vehiculo agregado exitosamente!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algo salio mal, intentelo de nuevo");
        }

    }//GEN-LAST:event_jb_AgregarVehiculoActionPerformed

    private void jb_AgregarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AgregarVendedorActionPerformed
        // TODO add your handling code here:
        try {
            String Nombre = jt_NombreVendedor.getText();
            int cantCarros = Integer.parseInt(jt_CantVendidosVend.getText());
            double dinGen = Double.parseDouble(jt_DineroGeneradoVendedor.getText());

            Vendedor ven = new Vendedor(Nombre, cantCarros, dinGen);
            vendedores.add(ven);

            jt_NombreVendedor.setText("");
            jt_CantVendidosVend.setText("");
            jt_DineroGeneradoVendedor.setText("");

            JOptionPane.showMessageDialog(this, "Vendedor agregado exitosamente!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algo salio mal, intentelo de nuevo");
        }
    }//GEN-LAST:event_jb_AgregarVendedorActionPerformed

    private void jb_AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AgregarClienteActionPerformed
        // TODO add your handling code here:
        try {
            String Nombre = jt_NombreCliente.getText();
            int Edad = Integer.parseInt(jt_EdadCliente.getText());
            String prof = jt_ProfesionCliente.getText();
            int carroscomp = Integer.parseInt(jt_CantCarrosCliente.getText());
            double sueldo = Double.parseDouble(jt_SueldoCliente.getText());

            Cliente c = new Cliente(Nombre, Edad, prof, carroscomp, sueldo);
            clientes.add(c);

            jt_NombreCliente.setText("");
            jt_EdadCliente.setText("");
            jt_ProfesionCliente.setText("");
            jt_CantCarrosCliente.setText("");
            jt_SueldoCliente.setText("");

            JOptionPane.showMessageDialog(this, "Cliente agregado exitosamente!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algo salio mal, intentelo de nuevo");
        }
    }//GEN-LAST:event_jb_AgregarClienteActionPerformed

    private void jb_AgregarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AgregarVentaActionPerformed
        // TODO add your handling code here:
        Vendedor ven = vendedores.get(cb_VendedoresDisponibles.getSelectedIndex());
        Vehiculo veh = carros.get(cb_VehiculosDisponibles.getSelectedIndex());
        Cliente cli = clientes.get(cb_ClientesDisponibles.getSelectedIndex());
        double cost = carros.get(cb_VehiculosDisponibles.getSelectedIndex()).getPrecioVenta();
        
        Venta venta = new Venta(ven, cli, cost, veh);
        ventas.add(venta);
        JOptionPane.showMessageDialog(this, "Venta realizada Exitosamente");
    }//GEN-LAST:event_jb_AgregarVentaActionPerformed

    private void jb_TerminarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_TerminarDiaActionPerformed
        // TODO add your handling code here:
        //pasar el arraylist de vehiculos a JSon format
        FileWriter fwCar = null;
        BufferedWriter bwCar = null;
        try {
            //siempre se sobre escribe el archivo
            fwCar = new FileWriter("./Vehiculos.txt", false);
            bwCar = new BufferedWriter(fwCar);
            for (int i = 0; i < carros.size(); i++) {
                bwCar.write("[\n");
                bwCar.write("\t"+carros.get(i).getMarca()+",\n");
                bwCar.write("\t"+carros.get(i).getModelo()+",\n");
                bwCar.write("\t"+carros.get(i).getColor()+",\n");
                bwCar.write("\t"+carros.get(i).getAño()+",\n");
                bwCar.write("\t"+carros.get(i).getPrecioVenta()+"\n");
                bwCar.write("];\n");
            }
            bwCar.flush();
        } catch (Exception ex) {
        }
        try {
            bwCar.close();
        } catch (IOException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fwCar.close();
        } catch (IOException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //lo mismo pero con los Vendedores:
        FileWriter fwVen = null;
        BufferedWriter bwVen = null;
        
        try {
            //siempre se sobre escribe el archivo
            fwVen = new FileWriter("./Vendedores.txt", false);
            bwVen = new BufferedWriter(fwVen);
            for (int i = 0; i < vendedores.size(); i++) {
                bwVen.write("[\n");
                bwVen.write("\t"+vendedores.get(i).getNombre()+",\n");
                bwVen.write("\t"+vendedores.get(i).getCantVendidos()+",\n");
                bwVen.write("\t"+vendedores.get(i).getDineroGenerado()+"\n");
                bwVen.write("];\n");
            }
            bwVen.flush();
        } catch (Exception ex) {
        }
        try {
            bwVen.close();
        } catch (IOException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fwVen.close();
        } catch (IOException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //ahora con clientes: 
        FileWriter fwCli = null;
        BufferedWriter bwCli = null;
        try {
            //siempre se sobre escribe el archivo
            fwCli = new FileWriter("./Clientes.txt", false);
            bwCli = new BufferedWriter(fwCli);
            for (int i = 0; i < clientes.size(); i++) {
                bwCli.write("[\n");
                bwCli.write("\t"+clientes.get(i).getNombre()+",\n");
                bwCli.write("\t"+clientes.get(i).getEdad()+",\n");
                bwCli.write("\t"+clientes.get(i).getProfesion()+",\n");
                bwCli.write("\t"+clientes.get(i).getCarrosComprados()+",\n");
                bwCli.write("\t"+clientes.get(i).getSueldoDisponible()+"\n");
                bwCli.write("];\n");
            }
            bwCli.flush();
        } catch (Exception ex) {
        }
        try {
            bwCli.close();
        } catch (IOException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fwCli.close();
        } catch (IOException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //ahora lo mismo pero con ventas... omfg
        FileWriter fwVenta = null;
        BufferedWriter bwVenta = null;
        
        try {
            //siempre se sobre escribe el archivo
            fwVenta = new FileWriter("./Ventas.txt", false);
            bwVenta = new BufferedWriter(fwVenta);
            for (int i = 0; i < ventas.size(); i++) {
                bwVenta.write("[\n");
                bwVenta.write("\t"+ventas.get(i).getVendedor().toString()+",\n");
                bwVenta.write("\t"+ventas.get(i).getCliente().toString()+",\n");
                bwVenta.write("\t"+ventas.get(i).getCosto_Transaccion()+",\n");
                bwVenta.write("\t"+ventas.get(i).getCarro().getMarca()+"\n");
                bwVenta.write("];\n");
            }
            bwVenta.flush();
        } catch (Exception ex) {
        }
        try {
            bwVenta.close();
        } catch (IOException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fwVenta.close();
        } catch (IOException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this, "Archivos de texto generados y o Modificados \nRevisar carpeta de proyecto :3\n (nuila tengo 5 niños judios en mi sotano) :3");
    }//GEN-LAST:event_jb_TerminarDiaActionPerformed

    private void jb_UpdateComboboxesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_UpdateComboboxesActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modeloVendedores = (DefaultComboBoxModel) cb_VendedoresDisponibles.getModel();
        for (int i = 0; i < vendedores.size(); i++) {
            modeloVendedores.addElement(vendedores.get(i).toString());
        }
        DefaultComboBoxModel modeloClientes = (DefaultComboBoxModel) cb_ClientesDisponibles.getModel();
        for (int i = 0; i < clientes.size(); i++) {
            modeloClientes.addElement(clientes.get(i).toString());
        }
        DefaultComboBoxModel modeloVehiculos = (DefaultComboBoxModel) cb_VehiculosDisponibles.getModel();
        for (int i = 0; i < carros.size(); i++) {
            modeloVehiculos.addElement(carros.get(i).toString());
        }
        cb_ClientesDisponibles.setModel(modeloClientes);
        cb_VehiculosDisponibles.setModel(modeloVehiculos);
        cb_VendedoresDisponibles.setModel(modeloVendedores);
    }//GEN-LAST:event_jb_UpdateComboboxesActionPerformed

    private void jb_listarVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_listarVendedoresActionPerformed
        // TODO add your handling code here:
        jt_editar.setText("");
        File vendedores = new File("./Vendedores.txt");
        String out = "";
        Scanner sc;
        try {
            sc = new Scanner(vendedores);
             try {
                while (sc.hasNext()) {
                    out += sc.next();
                }
            } catch (Exception ex) {
            }
            sc.close();
            jt_editar.setText(out);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_jb_listarVendedoresActionPerformed

    private void jb_ListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ListarClientesActionPerformed
        // TODO add your handling code here:
        jt_editar.setText("");
        File clientes = new File("./Clientes.txt");
        String out = "";
        Scanner sc;
        try {
            sc = new Scanner(clientes);
             try {
                while (sc.hasNext()) {
                    out += sc.next();
                }
            } catch (Exception ex) {
            }
            sc.close();
            jt_editar.setText(out);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_ListarClientesActionPerformed

    private void jb_listarVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_listarVehiculosActionPerformed
        // TODO add your handling code here:
        jt_editar.setText("");
        File carros = new File("./Vehiculos.txt");
        String out = "";
        Scanner sc;
        try {
            sc = new Scanner(carros);
             try {
                while (sc.hasNext()) {
                    out += sc.next();
                }
            } catch (Exception ex) {
            }
            sc.close();
            jt_editar.setText(out);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_listarVehiculosActionPerformed

    private void jb_listarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_listarVentasActionPerformed
        // TODO add your handling code here:
        jt_editar.setText("");
        File Ventas = new File("./Ventas.txt");
        String out = "";
        Scanner sc;
        try {
            sc = new Scanner(Ventas);
             try {
                while (sc.hasNext()) {
                    out += sc.next();
                }
            } catch (Exception ex) {
            }
            sc.close();
            jt_editar.setText(out);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Lab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_listarVentasActionPerformed

    private void jb_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_GuardarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Archivo Modificado Exitosamente!");
        jt_editar.setText("");
        //en realidad no se cambio nada... sory :3
    }//GEN-LAST:event_jb_GuardarActionPerformed

    private void jtree_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree_AdminMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Jeje... no programe los trees, sory :3");
    }//GEN-LAST:event_jtree_AdminMouseClicked

    private void jtree_DiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree_DiasMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Nope... este tampoco jajajaj.");
    }//GEN-LAST:event_jtree_DiasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab().setVisible(true);
            }
        });
    }

    public static void LeerVehiculos() throws IOException {
        File archivoVehiculos = null;
        FileReader fr = null;
        BufferedReader br = null;
        try {
            //absoluto:
            archivoVehiculos = new File("C:\\Users\\Diego Vasquez\\OneDrive\\Desktop\\Progra2\\Lab7P2_DiegoVasquez\\Vehiculos.txt");
            fr = new FileReader(archivoVehiculos);
            br = new BufferedReader(fr);
            String linea;
//            Scanner sc = null;
//            sc = new Scanner(archivoVehiculos);
            ArrayList<String> tokens = new ArrayList();
//            while(sc.hasNext()){
//                String next = sc.nextLine();
//                System.out.println(next+"++++");
//            }
//            sc.close();
            String dato = "";
            while ((linea = br.readLine()) != null) {
                if (!linea.contains(";")) {
                    dato += linea;
                }else{
                    dato+="\n]";
                    tokens.add(dato);
                    //System.out.println(dato);
                    dato="";
                }
            }
            for (int i = 0; i < tokens.size(); i++) {
                String veh = tokens.get(i).toString();
                String [] atr = veh.split(",");
                atr[0] = atr[0].substring(2, atr[0].length());
                atr[1] = atr[1].substring(1, atr[1].length());
                atr[2] = atr[2].substring(1, atr[2].length());
                atr[3] = atr[3].substring(1, atr[3].length());
                atr[4] = atr[4].substring(1, atr[4].length()-2);
                
                //System.out.println(atr[0] +"\n"+atr[1]+"\n"+atr[2]+"\n"+atr[3]+"\n"+atr[4]);
                Vehiculo carro = new Vehiculo(atr[0], atr[2], atr[1], Integer.parseInt(atr[3]), Double.parseDouble(atr[4]));
                carros.add(carro);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        //IMPORTANTE SIEMPRE "LIBERAR" EL ARCHIVO, INCLUSO SI FALLA
        br.close();
        fr.close();
    }
    
    public static void LeerVendedores() throws IOException{
        File archivoVendedores = null;
        FileReader fr = null;
        BufferedReader br = null;
        try {
            //absoluto:
            archivoVendedores = new File("C:\\Users\\Diego Vasquez\\OneDrive\\Desktop\\Progra2\\Lab7P2_DiegoVasquez\\Vendedores.txt");
            fr = new FileReader(archivoVendedores);
            br = new BufferedReader(fr);
            String linea;
//            Scanner sc = null;
//            sc = new Scanner(archivoVehiculos);
            ArrayList<String> tokens = new ArrayList();
//            while(sc.hasNext()){
//                String next = sc.nextLine();
//                System.out.println(next+"++++");
//            }
//            sc.close();
            String dato = "";
            while ((linea = br.readLine()) != null) {
                if (!linea.contains(";")) {
                    dato += linea;
                }else{
                    dato+="\n]";
                    tokens.add(dato);
                    //System.out.println(dato);
                    dato="";
                }
            }
            for (int i = 0; i < tokens.size(); i++) {
                String veh = tokens.get(i).toString();
                String [] atr = veh.split(",");
                atr[0] = atr[0].substring(2, atr[0].length());
                atr[1] = atr[1].substring(1, atr[1].length());
                atr[2] = atr[2].substring(1, atr[2].length()-2);
                
                //System.out.println(atr[0] +"\n"+atr[1]+"\n"+atr[2]);
                Vendedor ven = new Vendedor(atr[0], Integer.parseInt(atr[1]), Double.parseDouble(atr[2]));
                vendedores.add(ven);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        //IMPORTANTE SIEMPRE "LIBERAR" EL ARCHIVO, INCLUSO SI FALLA
        br.close();
        fr.close();
    }
    
    public static void LeerClientes() throws IOException{
        File archivoClientes = null;
        FileReader fr = null;
        BufferedReader br = null;
        try {
            //absoluto:
            archivoClientes = new File("C:\\Users\\Diego Vasquez\\OneDrive\\Desktop\\Progra2\\Lab7P2_DiegoVasquez\\Clientes.txt");
            fr = new FileReader(archivoClientes);
            br = new BufferedReader(fr);
            String linea;
//            Scanner sc = null;
//            sc = new Scanner(archivoVehiculos);
            ArrayList<String> tokens = new ArrayList();
//            while(sc.hasNext()){
//                String next = sc.nextLine();
//                System.out.println(next+"++++");
//            }
//            sc.close();
            String dato = "";
            while ((linea = br.readLine()) != null) {
                if (!linea.contains(";")) {
                    dato += linea;
                }else{
                    dato+="\n]";
                    tokens.add(dato);
                    //System.out.println(dato);
                    dato="";
                }
            }
            for (int i = 0; i < tokens.size(); i++) {
                String veh = tokens.get(i).toString();
                String [] atr = veh.split(",");
                atr[0] = atr[0].substring(2, atr[0].length());
                atr[1] = atr[1].substring(1, atr[1].length());
                atr[2] = atr[2].substring(1, atr[2].length());
                atr[3] = atr[3].substring(1, atr[3].length());
                atr[4] = atr[4].substring(1, atr[4].length()-2);
                
                //System.out.println(atr[0] +"\n"+atr[1]+"\n"+atr[2]+"\n"+atr[3]+"\n"+atr[4]);
                Cliente cli = new Cliente(atr[0], Integer.parseInt(atr[1]), atr[2], Integer.parseInt(atr[3]), Double.parseDouble(atr[4]));
                clientes.add(cli);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        //IMPORTANTE SIEMPRE "LIBERAR" EL ARCHIVO, INCLUSO SI FALLA
        br.close();
        fr.close();
    }
    
    public static void LeerVentas() throws IOException{
        File archivoVentas = null;
        FileReader fr = null;
        BufferedReader br = null;
        try {
            //absoluto:
            archivoVentas = new File("C:\\Users\\Diego Vasquez\\OneDrive\\Desktop\\Progra2\\Lab7P2_DiegoVasquez\\Ventas.txt");
            fr = new FileReader(archivoVentas);
            br = new BufferedReader(fr);
            String linea;
//            Scanner sc = null;
//            sc = new Scanner(archivoVehiculos);
            ArrayList<String> tokens = new ArrayList();
//            while(sc.hasNext()){
//                String next = sc.nextLine();
//                System.out.println(next+"++++");
//            }
//            sc.close();
            String dato = "";
            while ((linea = br.readLine()) != null) {
                if (!linea.contains(";")) {
                    dato += linea;
                }else{
                    dato+="\n]";
                    tokens.add(dato);
                    //System.out.println(dato);
                    dato="";
                }
            }
            for (int i = 0; i < tokens.size(); i++) {
                String veh = tokens.get(i).toString();
                String [] atr = veh.split(",");
                atr[0] = atr[0].substring(2, atr[0].length());
                atr[1] = atr[1].substring(1, atr[1].length());
                atr[2] = atr[2].substring(1, atr[2].length());
                atr[3] = atr[3].substring(1, atr[3].length()-2);
                
                Vendedor thisVen = null;
                Cliente thisCli = null;
                Vehiculo carro = null;
                
                //System.out.println(atr[0] +"\n"+atr[1]+"\n"+atr[2]+"\n"+atr[3]);
                //ver que vendedor es, segun el nombre
                for (int j = 0; j < vendedores.size(); j++) {
                    if(atr[0].equals(vendedores.get(j).getNombre())){
                        thisVen = vendedores.get(j);
                    }
                }//fin vendedor
                
                //ver que Cliente es, segun el nombre
                for (int j = 0; j < clientes.size(); j++) {
                    if(atr[1].equals(clientes.get(j).getNombre())){
                        thisCli = clientes.get(j);
                    }
                }//fin cliente
                
                //ver que vehiculo es segun el modelo
                for (int j = 0; j < carros.size(); j++) {
                    if(atr[3].equals(carros.get(j).getMarca())){
                        carro = carros.get(j);
                    }
                }//fin carros
                
                //hacer la venta y pasarla al arraylist
                Venta venta = new Venta(thisVen, thisCli, Double.parseDouble(atr[2]), carro);
                ventas.add(venta);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        //IMPORTANTE SIEMPRE "LIBERAR" EL ARCHIVO, INCLUSO SI FALLA
        br.close();
        fr.close();
    }

    static ArrayList<Vehiculo> carros = new ArrayList();
    static ArrayList<Cliente> clientes = new ArrayList();
    static ArrayList<Vendedor> vendedores = new ArrayList();
    static ArrayList<Venta> ventas = new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_ColorVehiculo;
    private javax.swing.JLabel JL_EdadCliente;
    private javax.swing.JComboBox<String> cb_ClientesDisponibles;
    private javax.swing.JComboBox<String> cb_VehiculosDisponibles;
    private javax.swing.JComboBox<String> cb_VendedoresDisponibles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jb_AgregarCliente;
    private javax.swing.JButton jb_AgregarVehiculo;
    private javax.swing.JButton jb_AgregarVendedor;
    private javax.swing.JButton jb_AgregarVenta;
    private javax.swing.JButton jb_Guardar;
    private javax.swing.JButton jb_ListarClientes;
    private javax.swing.JButton jb_TerminarDia;
    private javax.swing.JButton jb_UpdateComboboxes;
    private javax.swing.JButton jb_listarVehiculos;
    private javax.swing.JButton jb_listarVendedores;
    private javax.swing.JButton jb_listarVentas;
    private javax.swing.JLabel jl_CantCarrosCliente;
    private javax.swing.JLabel jl_CantVendidosVendedor;
    private javax.swing.JLabel jl_ClientesDisp;
    private javax.swing.JLabel jl_DineroGeneradoVendedor;
    private javax.swing.JLabel jl_ListarClientes;
    private javax.swing.JLabel jl_ListarVehiculos;
    private javax.swing.JLabel jl_ListarVendedores;
    private javax.swing.JLabel jl_ListarVentas;
    private javax.swing.JLabel jl_Marca;
    private javax.swing.JLabel jl_NombreCliente;
    private javax.swing.JLabel jl_NombreVendedor;
    private javax.swing.JLabel jl_ProfesionCliente;
    private javax.swing.JLabel jl_SueldoCliente;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JLabel jl_Titulo1;
    private javax.swing.JLabel jl_Titulo2;
    private javax.swing.JLabel jl_Titulo3;
    private javax.swing.JLabel jl_VehiculosDisponibles;
    private javax.swing.JLabel jl_VendedoresDisponibles;
    private javax.swing.JLabel jl_años;
    private javax.swing.JLabel jl_modelo;
    private javax.swing.JLabel jl_precio;
    private javax.swing.JPanel jp_BackGround;
    private javax.swing.JPanel jp_Clientes;
    private javax.swing.JPanel jp_Jtrees;
    private javax.swing.JPanel jp_TextPane;
    private javax.swing.JPanel jp_Vehiculos;
    private javax.swing.JPanel jp_Vendedores;
    private javax.swing.JPanel jp_Venta;
    private javax.swing.JTextField jt_Años;
    private javax.swing.JTextField jt_CantCarrosCliente;
    private javax.swing.JTextField jt_CantVendidosVend;
    private javax.swing.JTextField jt_ColorCarro;
    private javax.swing.JTextField jt_DineroGeneradoVendedor;
    private javax.swing.JTextField jt_EdadCliente;
    private javax.swing.JTextField jt_Marca;
    private javax.swing.JTextField jt_Modelo;
    private javax.swing.JTextField jt_NombreCliente;
    private javax.swing.JTextField jt_NombreVendedor;
    private javax.swing.JTextField jt_Precio;
    private javax.swing.JTextField jt_ProfesionCliente;
    private javax.swing.JTextField jt_SueldoCliente;
    private javax.swing.JTabbedPane jt_YUH;
    private javax.swing.JTextPane jt_editar;
    private javax.swing.JTree jtree_Admin;
    private javax.swing.JTree jtree_Dias;
    // End of variables declaration//GEN-END:variables
}
